require("mappings")
require("options")

require("config.lazy")
require("config.lsp")
require("config.cmp")
require("config.conform")
require("config.harpoon")
require("config.telescope")
require("config.autopair")
require("config.barbar")
require("config.github")
--require('config.tokyonight')
--require('config.everforest')
require("config.treesitter")
require("config.lualine")
require("config.blankline")
require("config.neotree")
