require('mappings')
require('options')

require('config.lazy')
require('config.lsp')
require('config.cmp')
require('config.conform')
require('config.harpoon')
require('config.telescope')
require('config.github')
--require('config.tokyonight')
--require('config.everforest')
require('config.treesitter')
require('config.blankline')
require('config.lualine')
require('config.neotree')
require('config.autopair')
